<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project [
		<!ELEMENT project (modelVersion|parent|groupId|artifactId|version|name|description|dependencies|build)*>
		<!ATTLIST project
				xmlns CDATA #REQUIRED
				xmlns:xsi CDATA #REQUIRED
				xsi:schemaLocation CDATA #REQUIRED>
		<!ELEMENT modelVersion (#PCDATA)>
		<!ELEMENT parent (groupId|artifactId|version|relativePath)*>
		<!ELEMENT groupId (#PCDATA)>
		<!ELEMENT artifactId (#PCDATA)>
		<!ELEMENT version (#PCDATA)>
		<!ELEMENT relativePath (#PCDATA)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT dependencies (dependency)*>
		<!ELEMENT dependency (groupId|artifactId|scope|optional|version)*>
		<!ELEMENT scope (#PCDATA)>
		<!ELEMENT optional (#PCDATA)>
		<!ELEMENT build (plugins)*>
		<!ELEMENT plugins (plugin)*>
		<!ELEMENT plugin (groupId|artifactId|configuration|executions)*>
		<!ELEMENT configuration (excludes|outputDirectory|resources|mainClass|includeSystemScope)*>
		<!ELEMENT excludes (exclude)*>
		<!ELEMENT exclude (groupId|artifactId)*>
		<!ELEMENT mainClass (#PCDATA)>
		<!ELEMENT includeSystemScope (#PCDATA)>
		<!ELEMENT executions (execution)*>
		<!ELEMENT execution (id|phase|goals|configuration)*>
		<!ELEMENT id (#PCDATA)>
		<!ELEMENT phase (#PCDATA)>
		<!ELEMENT goals (goal)*>
		<!ELEMENT goal (#PCDATA)>
		<!ELEMENT outputDirectory (#PCDATA)>
		<!ELEMENT resources (resource)*>
		<!ELEMENT resource (directory|include|filtering)*>
		<!ELEMENT directory (#PCDATA)>
		<!ELEMENT include (#PCDATA)>
		<!ELEMENT filtering (#PCDATA)>
		]>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.finastra.loaniq</groupId>
		<artifactId>liq_version</artifactId>
		<version>1.0.0</version>
		<relativePath>../liq_version/pom.xml</relativePath>
	</parent>
	<groupId>com.finastra.tool</groupId>
	<artifactId>IntegrationAPITool</artifactId>
	<version>1.0</version>
	<name>IntegrationAPITool</name>
	<description>Demo project for Spring Boot</description>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.2.3</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.2.3</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<mainClass>com.finastra.integrationapi.tool.ExcelReader</mainClass>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
				<executions>
					<execution>
						<id>repackage</id>
						<phase>package</phase>
						<goals>
							<goal>repackage</goal>
						</goals>
						<configuration>
							<includeSystemScope>true</includeSystemScope>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-files-on-build</id>
						<phase>package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${basedir}/artifacts/executable</outputDirectory>
							<resources>
								<resource>
									<directory>${basedir}/target</directory>
									<include>IntegrationAPITool-1.0.jar</include>
									<filtering>false</filtering>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
