name: my-first-workflow
on: 
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - dev
      - 'feature-*'

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          pwd
          ls -ltr
          hostname
      - name: Checkout
        uses: actions/checkout@v6.0.3
      - name: Step 3
        run: |
          pwd
          ls -ltr
          hostname

  job2:
    name: Echo message
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo 'my name is amitesh'
      - name: Step 2
        run: exit 1
    
      
